services:

  bws_init:
    build: ./bws
    volumes:
      - ./secrets/bws_token.txt:/secrets/bws_token.txt:ro
      - runtime_secrets:/runtime-secrets
    restart: "no"

  migrate:
    volumes:
      - runtime_secrets:/app/secrets:ro
    env_file:
      - .env-docker/.env.prod
    depends_on:
      bws_init:
        condition: service_completed_successfully

  web:
    volumes:
      - static_volume:/app/staticfiles
      - runtime_secrets:/app/secrets:ro
    env_file:
      - .env-docker/.env.prod
    depends_on:
      bws_init:
        condition: service_completed_successfully

  db:
    volumes:
      - postgres_data:/var/lib/postgresql
      - runtime_secrets:/run/secrets:ro
    env_file:
      - .env-docker/.env.db
    restart: unless-stopped
    depends_on:
      bws_init:
        condition: service_completed_successfully

  celery_worker:
    volumes:
      - runtime_secrets:/app/secrets:ro
    env_file:
      - .env-docker/.env.prod
    restart: unless-stopped

  celery_beat:
    volumes:
      - runtime_secrets:/app/secrets:ro
    env_file:
      - .env-docker/.env.prod
    restart: unless-stopped

  nginx:
    volumes:
      - static_volume:/static
      - ./nginx.prod.conf:/etc/nginx/conf.d/default.conf
      - runtime_secrets:/etc/nginx/secrets:ro
    restart: unless-stopped