services:

  migrate:
    volumes:
      - .:/app
      - ./secrets:/app/secrets:ro
    env_file:
      - .env-docker/.env.dev

  web: 
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - ./secrets:/app/secrets:ro
    env_file:
      - .env-docker/.env.dev

  db:
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./secrets:/run/secrets:ro
    env_file:
      - .env-docker/.env.db
    ports:
      - "5432:5432"

  celery_worker:
    volumes:
      - .:/app
      - ./secrets:/app/secrets:ro
    env_file:
      - .env-docker/.env.dev

  celery_beat:
    volumes:
      - .:/app
      - ./secrets:/app/secrets:ro
    env_file:
      - .env-docker/.env.dev

  nginx:
    volumes:
      - static_volume:/app/staticfiles
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./secrets/.htpasswd:/etc/nginx/secrets/.htpasswd:ro
