services:

  migrate:
    build: .
    command: python manage.py migrate --noinput
    depends_on:
      db:
        condition: service_healthy 

  web:
    build: .
    depends_on:
      migrate:
        condition: service_completed_successfully


  db:
    image: postgres:18
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $(cat /run/secrets/postgres_user.txt) -d $(cat /run/secrets/postgres_db.txt)"]
      interval: 5s
      timeout: 5s
      retries: 5

  celery_worker:
    build: .
    command: celery -A core worker --loglevel=info --concurrency=1
    depends_on:
      migrate:
        condition: service_completed_successfully

  celery_beat:
    build: .
    command: celery -A core beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    depends_on:
      migrate:
        condition: service_completed_successfully
      
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  runtime_secrets: