# Generated by Django 6.0.5 on 2026-05-27 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='depositclient',
            options={'verbose_name': 'Client deposit', 'verbose_name_plural': 'Client deposits'},
        ),
        migrations.AlterModelOptions(
            name='depositfactory',
            options={'verbose_name': 'Factory deposit', 'verbose_name_plural': 'Factory deposits'},
        ),
        migrations.AlterModelOptions(
            name='transport',
            options={'verbose_name': 'Transport', 'verbose_name_plural': 'Transports'},
        ),
        migrations.AddField(
            model_name='transport',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transport',
            name='reminder_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
    ]
