# Generated by Django 6.0.5 on 2026-05-27 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_depositclient_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositclient',
            name='payment_due_by',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='depositclient',
            name='reminder_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='depositfactory',
            name='payment_due_by',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='depositfactory',
            name='reminder_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
