# Generated by Django 6.0.5 on 2026-06-23 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_depositclient_payment_due_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientorder',
            name='client_contact',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='clientorder',
            name='client_representative',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='clientorder',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='depositclient',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='depositfactory',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='factoryorder',
            name='factory_order_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='factoryorder',
            name='order_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='factoryorder',
            name='production_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='factoryorder',
            name='production_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
