# Generated by Django 6.0.5 on 2026-06-30 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_clientorder_client_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factoryorder',
            name='furniture_start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='factoryorder',
            name='is_furniture_reminder_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='factoryorder',
            name='is_package_clarification_reminder_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='factoryorder',
            name='package_clarification_reminder_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
    ]
