# Generated by Django 6.0.5 on 2026-06-30 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_factoryorder_furniture_start_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factoryorder',
            old_name='furniture_start_date',
            new_name='furniture_reminder_date',
        ),
    ]
