# Generated by Django 6.0.5 on 2026-07-07 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_furniture_start_date_factoryorder_furniture_reminder_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientorder',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('Visa suma', 'Visa suma'), ('Avansas', 'Avansas'), ('Po pristatymo', 'Po pristatymo')], default='', max_length=50),
        ),
    ]
