# Generated by Django 6.0.6 on 2026-08-04 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_clientorder_payment_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recoverycode',
            name='invalidated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
