# Generated by Django 6.0.6 on 2026-08-06 20:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_recoverycode_invalidated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecoveryAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('code_verified', 'Code verified'), ('password_reset', 'Password reset completed'), ('failed_lockout', 'Failed — locked out'), ('failed_no_phone', 'Failed — no phone on file'), ('failed_invalid_code', 'Failed — invalid/expired code'), ('failed_sms_error', 'Failed — SMS send error')], default='initiated', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('detail', models.TextField(blank=True, help_text='Error message or extra context, if any.')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
