# Generated by Django 6.0.6 on 2026-08-06 21:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_recoveryattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='recoveryattempt',
            name='session_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
