# Generated by Django 6.0.6 on 2026-08-06 22:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_recoveryattempt_session_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recoveryattempt',
            name='session_id',
        ),
        migrations.CreateModel(
            name='RecoverySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, help_text='When the recovery session was completed (successfully or not).', null=True)),
                ('result', models.CharField(choices=[('active', 'Active'), ('success', 'Success'), ('failed', 'Failed')], default='active', max_length=10)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address from which the recovery session was initiated.', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='recoveryattempt',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='main.recoverysession'),
        ),
    ]
