# Generated by Django 6.0.6 on 2026-08-07 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_recoveryattempt_session_id_recoverysession_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NtfySentReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_id', models.CharField(max_length=100, unique=True)),
                ('last_sent_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
