# Generated by Django 6.0.6 on 2026-08-15 10:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_ntfysentreminder'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('lt', 'Lietuvių')], default='en', max_length=5)),
            ],
            options={
                'verbose_name': 'Site settings',
                'verbose_name_plural': 'Site settings',
            },
        ),
        migrations.AlterField(
            model_name='ntfysentreminder',
            name='last_sent_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
