# Generated by Django 6.0.6 on 2026-08-16 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_sitesettings_delete_apitoken_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApiToken',
        ),
    ]
