# Generated by Django 6.0.7 on 2026-09-05 09:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_delete_apitoken'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['client_name'], name='main_client_client__63071b_idx'),
        ),
        migrations.AddIndex(
            model_name='depositclient',
            index=models.Index(condition=models.Q(('is_reminder_sent', False)), fields=['reminder_date'], name='depositclient_unsent_idx'),
        ),
        migrations.AddIndex(
            model_name='depositfactory',
            index=models.Index(condition=models.Q(('is_reminder_sent', False)), fields=['reminder_date'], name='depositfactory_unsent_idx'),
        ),
        migrations.AddIndex(
            model_name='factoryorder',
            index=models.Index(condition=models.Q(('is_furniture_reminder_sent', False)), fields=['furniture_reminder_date'], name='fo_furniture_unsent_idx'),
        ),
        migrations.AddIndex(
            model_name='factoryorder',
            index=models.Index(condition=models.Q(('is_package_clarification_reminder_sent', False)), fields=['package_clarification_reminder_date'], name='fo_package_unsent_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['-created_at'], name='main_order_created_49eb22_idx'),
        ),
        migrations.AddIndex(
            model_name='recoverycode',
            index=models.Index(condition=models.Q(('invalidated_at__isnull', True), ('used_at__isnull', True)), fields=['user'], name='recoverycode_active_idx'),
        ),
        migrations.AddIndex(
            model_name='recoverysession',
            index=models.Index(fields=['user', '-started_at'], name='main_recove_user_id_09f0bb_idx'),
        ),
        migrations.AddIndex(
            model_name='transport',
            index=models.Index(condition=models.Q(('is_reminder_sent', False)), fields=['reminder_date'], name='transport_unsent_reminder_idx'),
        ),
    ]
