# Generated by Django 6.0.7 on 2026-09-07 09:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_fix_payment_type_values'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientorder',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('visa_suma', 'Visa suma'), ('avansas', 'Avansas'), ('po_pristatymo', 'Po pristatymo')], default='', max_length=50),
        ),
        migrations.AddIndex(
            model_name='recoveryattempt',
            index=models.Index(fields=['session', 'created_at'], name='main_recove_session_534081_idx'),
        ),
    ]
