# Generated by Django 6.0.8 on 2026-10-02 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_clientorder_payment_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='is_sent',
            field=models.BooleanField(default=False),
        ),
    ]
